"""contract/ から Python のデータと Swift の型を生成する。"""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from pathlib import Path

from rosbags.interfaces import Nodetype
from rosbags.typesys.msg import get_types_from_msg

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTRACT = REPO_ROOT / "contract"
MSG_ROOT = CONTRACT / "msg"
PY_GENERATED = REPO_ROOT / "python" / "src" / "pocketsensor" / "_generated"
SWIFT_GENERATED = REPO_ROOT / "ios" / "PocketSensorKit" / "Sources" / "PocketSensorCore" / "Generated"

HEADER = "Generated by tools/gen_contract.py. Do not edit."
SCHEMA_SEP = "=" * 80

CHANNEL_KEYS = (
    "key",
    "topic",
    "schema",
    "frame_id",
    "child_frame_id",
    "rate_param",
    "rate_hz",
    "backpressure",
    "queue_seconds",
    "group",
    "latched",
    "stage",
)
PARAMETER_KEYS = (
    "name",
    "type",
    "default",
    "min",
    "max",
    "choices",
    "writable",
    "description",
)
SERVICE_KEYS = ("key", "name", "type", "stage")

PRIMITIVE_SWIFT = {
    "bool": ("Bool", "false"),
    "byte": ("UInt8", "0"),
    "char": ("UInt8", "0"),
    "uint8": ("UInt8", "0"),
    "int8": ("Int8", "0"),
    "uint16": ("UInt16", "0"),
    "int16": ("Int16", "0"),
    "uint32": ("UInt32", "0"),
    "int32": ("Int32", "0"),
    "uint64": ("UInt64", "0"),
    "int64": ("Int64", "0"),
    "float32": ("Float", "0"),
    "float64": ("Double", "0"),
    "string": ("Swift.String", '""'),
}

SWIFT_KEYWORDS = {
    "Any",
    "Protocol",
    "Self",
    "Type",
    "actor",
    "as",
    "assignment",
    "associatedtype",
    "associativity",
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "continue",
    "convenience",
    "default",
    "defer",
    "deinit",
    "didSet",
    "do",
    "dynamic",
    "else",
    "enum",
    "extension",
    "fallthrough",
    "false",
    "fileprivate",
    "final",
    "for",
    "func",
    "get",
    "guard",
    "higherThan",
    "if",
    "import",
    "in",
    "indirect",
    "infix",
    "init",
    "inout",
    "internal",
    "is",
    "isolated",
    "lazy",
    "left",
    "let",
    "lowerThan",
    "mutating",
    "nil",
    "none",
    "nonisolated",
    "nonmutating",
    "open",
    "operator",
    "optional",
    "override",
    "package",
    "postfix",
    "precedence",
    "precedencegroup",
    "prefix",
    "private",
    "protocol",
    "public",
    "repeat",
    "required",
    "rethrows",
    "return",
    "right",
    "self",
    "set",
    "some",
    "static",
    "struct",
    "subscript",
    "super",
    "switch",
    "throw",
    "throws",
    "true",
    "try",
    "typealias",
    "unowned",
    "var",
    "weak",
    "where",
    "while",
    "willSet",
}


def swift_escape(name: str) -> str:
    return f"`{name}`" if name in SWIFT_KEYWORDS else name


def snake_to_camel(name: str) -> str:
    parts = name.split("_")
    head = parts[0].lower()
    tail = "".join(p[:1].upper() + p[1:].lower() for p in parts[1:] if p)
    return head + tail


def pkg_enum_name(pkg: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in pkg.split("_"))


def split_typename(typename: str) -> tuple[str, str, str]:
    pkg, kind, name = typename.split("/")
    return pkg, kind, name


def short_schema_label(typename: str) -> str:
    pkg, _kind, name = split_typename(typename)
    return f"{pkg}/{name}"


def parse_name_for_rosbags(canonical: str) -> str:
    return canonical.replace("/srv/", "/msg/")


def normalize_raw(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    if text.endswith("\n"):
        return text.rstrip("\n") + "\n"
    return text + "\n"


def split_srv(text: str) -> tuple[str, str]:
    lines = text.replace("\r\n", "\n").replace("\r", "\n").splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.rstrip("\n") == "---":
            return "".join(lines[:i]), "".join(lines[i + 1 :])
    raise ValueError("service definition has no --- separator")


def load_msg_texts() -> dict[str, str]:
    texts: dict[str, str] = {}
    for path in sorted(MSG_ROOT.rglob("*")):
        if path.suffix == ".msg":
            rel = path.relative_to(MSG_ROOT)
            pkg = rel.parts[0]
            name = path.stem
            texts[f"{pkg}/msg/{name}"] = path.read_text(encoding="utf-8")
        elif path.suffix == ".srv":
            rel = path.relative_to(MSG_ROOT)
            pkg = rel.parts[0]
            name = path.stem
            req, resp = split_srv(path.read_text(encoding="utf-8"))
            texts[f"{pkg}/srv/{name}_Request"] = req
            texts[f"{pkg}/srv/{name}_Response"] = resp
    return texts


def parse_types(msg_texts: dict[str, str]) -> dict:
    types: dict = {}
    for canonical, raw in msg_texts.items():
        parse_name = parse_name_for_rosbags(canonical)
        parsed = get_types_from_msg(raw, parse_name)
        for key, value in parsed.items():
            types[canonical if key == parse_name else key] = value
    return types


def named_types(desc: object) -> list[str]:
    kind = desc[0]
    if kind == Nodetype.NAME:
        return [desc[1]]
    if kind in (Nodetype.ARRAY, Nodetype.SEQUENCE):
        inner, _n = desc[1]
        if inner[0] == Nodetype.NAME:
            return [inner[1]]
    return []


def collect_deps(root: str, types: dict) -> list[str]:
    ordered: list[str] = []
    seen = {root}

    def walk(name: str) -> None:
        _consts, fields = types[name]
        for _fname, desc in fields:
            for child in named_types(desc):
                if child not in seen:
                    seen.add(child)
                    ordered.append(child)
                    walk(child)

    walk(root)
    return ordered


def schema_text_for(name: str, msg_texts: dict[str, str], types: dict) -> str:
    chunks = [normalize_raw(msg_texts[name])]
    for dep in collect_deps(name, types):
        chunks.append(SCHEMA_SEP + "\n")
        chunks.append(f"MSG: {short_schema_label(dep)}\n")
        chunks.append(normalize_raw(msg_texts[dep]))
    return "".join(chunks)


def fill_rows(rows: list[dict], keys: tuple[str, ...]) -> list[dict]:
    extra: set[str] = set()
    for row in rows:
        extra.update(row.keys())
    extra -= set(keys)
    ordered = list(keys) + sorted(extra)
    filled = []
    for row in rows:
        filled.append({key: row.get(key) for key in ordered})
    return filled


def load_toml_table(path: Path, key: str) -> list[dict]:
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    return list(data.get(key, []))


def py_str(s: str, indent: int) -> str:
    budget = max(24, 100 - indent)
    chunks: list[str] = []
    buf = ""
    for ch in s:
        candidate = buf + ch
        if len(json.dumps(candidate, ensure_ascii=False)) > budget and buf:
            chunks.append(buf)
            buf = ch
        else:
            buf = candidate
    if buf or not chunks:
        chunks.append(buf)
    if len(chunks) == 1:
        dumped = json.dumps(chunks[0], ensure_ascii=False)
        if indent + len(dumped) <= 110:
            return dumped
    lines = ["("]
    pad = " " * (indent + 4)
    for chunk in chunks:
        lines.append(pad + json.dumps(chunk, ensure_ascii=False))
    lines.append(" " * indent + ")")
    return "\n".join(lines)


def py_value(obj: object, indent: int) -> str:
    if obj is None:
        return "None"
    if obj is True:
        return "True"
    if obj is False:
        return "False"
    if isinstance(obj, str):
        return py_str(obj, indent)
    if isinstance(obj, int) and not isinstance(obj, bool):
        return str(obj)
    if isinstance(obj, float):
        return repr(obj)
    if isinstance(obj, list):
        if not obj:
            return "[]"
        inner = ", ".join(py_value(item, indent + 4) for item in obj)
        return f"[{inner}]"
    if isinstance(obj, dict):
        if not obj:
            return "{}"
        pad = " " * (indent + 4)
        closer = " " * indent
        lines = ["{"]
        items = list(obj.items())
        for i, (key, val) in enumerate(items):
            comma = "," if i < len(items) - 1 else ","
            lines.append(f"{pad}{py_str(key, indent + 4)}: {py_value(val, indent + 8)}{comma}")
        lines.append(closer + "}")
        return "\n".join(lines)
    raise TypeError(f"cannot emit {type(obj)!r}")


def emit_py_dict_of_str(name: str, mapping: dict[str, str]) -> str:
    lines = [f"{name}: dict[str, str] = {{"]
    for key in sorted(mapping):
        lines.append(f"    {json.dumps(key)}: {py_str(mapping[key], 4)},")
    lines.append("}")
    return "\n".join(lines)


def emit_py_rows(name: str, rows: list[dict]) -> str:
    lines = [f"{name}: tuple[dict[str, object], ...] = ("]
    for row in rows:
        emitted = py_value(row, 4)
        lines.append(f"    {emitted},")
    if not rows:
        lines.append(")")
        return "\n".join(lines)
    lines.append(")")
    return "\n".join(lines)


def generate_python(
    msg_texts: dict[str, str],
    schema_texts: dict[str, str],
    channels: list[dict],
    parameters: list[dict],
    services: list[dict],
) -> str:
    parts = [
        f"# {HEADER}",
        "",
        "from __future__ import annotations",
        "",
        emit_py_dict_of_str("MSG_TEXTS", msg_texts),
        "",
        emit_py_dict_of_str("SCHEMA_TEXTS", schema_texts),
        "",
        emit_py_rows("CHANNELS", channels),
        "",
        emit_py_rows("PARAMETERS", parameters),
        "",
        emit_py_rows("SERVICES", services),
        "",
    ]
    return "\n".join(parts)


def swift_string(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def swift_pkg_of(typename: str) -> str:
    return pkg_enum_name(split_typename(typename)[0])


def swift_nominal(typename: str) -> str:
    pkg, kind, name = split_typename(typename)
    enum = pkg_enum_name(pkg)
    if kind == "srv":
        if name.endswith("_Request"):
            return f"{enum}.{name[: -len('_Request')]}.Request"
        if name.endswith("_Response"):
            return f"{enum}.{name[: -len('_Response')]}.Response"
    return f"{enum}.{name}"


def bounded_string(desc: object) -> None:
    if desc[0] == Nodetype.BASE:
        basename, limit = desc[1]
        if basename == "string" and limit:
            raise ValueError("bounded strings are unused and unsupported")
        if basename == "wstring":
            raise ValueError("wstring is unused and unsupported")
    if desc[0] in (Nodetype.ARRAY, Nodetype.SEQUENCE):
        bounded_string(desc[1][0])


def is_byte_sequence(desc: object) -> bool:
    if desc[0] != Nodetype.SEQUENCE:
        return False
    inner, _n = desc[1]
    return inner[0] == Nodetype.BASE and inner[1][0] in {"uint8", "byte"}


def typed_elem_zero(swift_type: str, generic_zero: str) -> str:
    if swift_type in {
        "UInt8",
        "Int8",
        "UInt16",
        "Int16",
        "UInt32",
        "Int32",
        "UInt64",
        "Int64",
        "Float",
        "Double",
    }:
        return f"{swift_type}(0)"
    return generic_zero


def field_swift(desc: object) -> tuple[str, str, str, int | None, str]:
    """Return (swift_type, init_zero, encode_kind, fixed_count, elem_zero)."""
    bounded_string(desc)
    kind = desc[0]
    if kind == Nodetype.BASE:
        basename = desc[1][0]
        if basename not in PRIMITIVE_SWIFT:
            raise ValueError(f"unsupported primitive {basename}")
        typ, zero = PRIMITIVE_SWIFT[basename]
        return typ, zero, "primitive", None, typed_elem_zero(typ, zero)
    if kind == Nodetype.NAME:
        typ = swift_nominal(desc[1])
        z = f"{typ}()"
        return typ, z, "nested", None, z
    inner, count = desc[1]
    if kind == Nodetype.SEQUENCE:
        if is_byte_sequence(desc):
            return "Data", "Data()", "data", None, "Data()"
        elem, _init, _k, _n, elem_zero = field_swift(inner)
        return f"[{elem}]", "[]", "sequence", None, elem_zero
    if kind == Nodetype.ARRAY:
        elem, _init, _k, _n, elem_zero = field_swift(inner)
        init_zero = f"Array(repeating: {elem_zero}, count: {count})"
        return f"[{elem}]", init_zero, "fixed", count, elem_zero
    raise ValueError(f"unsupported field desc {desc!r}")


def const_swift_type(basename: str) -> str:
    return PRIMITIVE_SWIFT[basename][0]


def emit_swift_struct(typename: str, consts: list, fields: list) -> tuple[list[str], list]:
    pkg, kind, name = split_typename(typename)
    _ = pkg
    type_name = name
    if kind == "srv":
        type_name = "Request" if name.endswith("_Request") else "Response"
    lines = [
        f"    public struct {type_name}: CDRCodable, Equatable, Sendable {{",
        f"        public static let schemaName = {swift_string(typename)}",
    ]
    for cname, ctype, cvalue in consts:
        swift_c = swift_escape(snake_to_camel(cname))
        if isinstance(cvalue, bool):
            raise ValueError("bool constants are unused")
        if isinstance(cvalue, str):
            rendered = swift_string(cvalue)
        else:
            rendered = str(cvalue)
        lines.append(f"        public static let {swift_c}: {const_swift_type(ctype)} = {rendered}")

    field_infos = []
    for fname, desc in fields:
        swift_type, init_zero, encode_kind, fixed, elem_zero = field_swift(desc)
        swift_f = swift_escape(snake_to_camel(fname))
        field_infos.append((swift_f, swift_type, init_zero, encode_kind, fixed, elem_zero))
        lines.append(f"        public var {swift_f}: {swift_type}")

    if field_infos:
        lines.append("")
        lines.append("        public init(")
        for i, (swift_f, swift_type, init_zero, _k, _n, _ez) in enumerate(field_infos):
            comma = "," if i < len(field_infos) - 1 else ""
            lines.append(f"            {swift_f}: {swift_type} = {init_zero}{comma}")
        lines.append("        ) {")
        for swift_f, _t, _z, _k, _n, _ez in field_infos:
            lines.append(f"            self.{swift_f} = {swift_f}")
        lines.append("        }")
    else:
        lines.append("")
        lines.append("        public init() {}")

    lines.append("")
    lines.extend(emit_encode_decode(field_infos))
    return lines, field_infos


def emit_encode_decode(field_infos: list) -> list[str]:
    lines = ["        public func encode(to encoder: inout CDREncoder) {"]
    if not field_infos:
        lines.append("            encoder.encode(UInt8(0))")
    else:
        for swift_f, _t, _init, encode_kind, fixed, elem_zero in field_infos:
            if encode_kind == "sequence":
                lines.append(f"            encoder.encodeSequence({swift_f})")
            elif encode_kind == "fixed":
                lines.append(
                    f"            encoder.encodeFixedArray({swift_f}, count: {fixed}, zero: {elem_zero})"
                )
            else:
                lines.append(f"            encoder.encode({swift_f})")
    lines.append("        }")
    lines.append("")
    lines.append("        public init(from decoder: inout CDRDecoder) throws {")
    if not field_infos:
        lines.append("            if decoder.remaining > 0 {")
        lines.append("                _ = try decoder.decode(UInt8.self)")
        lines.append("            }")
    else:
        for swift_f, swift_type, _init, encode_kind, fixed, _ez in field_infos:
            if encode_kind == "sequence":
                inner = swift_type[1:-1]
                lines.append(f"            self.{swift_f} = try decoder.decodeSequence({inner}.self)")
            elif encode_kind == "fixed":
                inner = swift_type[1:-1]
                lines.append(
                    f"            self.{swift_f} = try decoder.decodeFixedArray({inner}.self, count: {fixed})"
                )
            else:
                lines.append(f"            self.{swift_f} = try decoder.decode({swift_type}.self)")
    lines.append("        }")
    lines.append("    }")
    return lines


def generate_messages_swift(msg_texts: dict[str, str], types: dict) -> str:
    by_pkg: dict[str, list[list[str]]] = {}
    services: dict[str, dict[str, list[tuple[str, list[str]]]]] = {}
    for typename in sorted(types):
        pkg, kind, name = split_typename(typename)
        consts, fields = types[typename]
        struct_lines, _field_infos = emit_swift_struct(typename, consts, fields)
        if kind == "srv":
            svc = name[: -len("_Request")] if name.endswith("_Request") else name[: -len("_Response")]
            services.setdefault(pkg, {}).setdefault(svc, [])
            services[pkg][svc].append((name, struct_lines))
        else:
            by_pkg.setdefault(pkg, []).append(struct_lines)

    out = [f"// {HEADER}", "", "import Foundation", ""]
    for pkg in sorted(set(by_pkg) | set(services)):
        out.append(f"public enum {pkg_enum_name(pkg)} {{")
        for struct_lines in by_pkg.get(pkg, []):
            out.extend(struct_lines)
            out.append("")
        for svc in sorted(services.get(pkg, {})):
            out.append(f"    public enum {svc} {{")
            halves = services[pkg][svc]
            halves.sort(key=lambda item: item[0])
            for _name, body in halves:
                # body is indented with 4 spaces for struct; nest one more level
                for line in body:
                    if line == "":
                        out.append("")
                    else:
                        out.append("    " + line)
                out.append("")
            out.append("    }")
            out.append("")
        # trim extra blank before close
        while out[-1] == "":
            out.pop()
        out.append("}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def swift_optional(value: object, as_type: str) -> str:
    if value is None:
        return "nil"
    if as_type == "String":
        return swift_string(str(value))
    if as_type == "Double":
        return repr(float(value))
    if as_type == "[String]":
        inner = ", ".join(swift_string(str(item)) for item in value)  # type: ignore[union-attr]
        return f"[{inner}]"
    if as_type == "Int":
        return str(int(value))  # type: ignore[arg-type]
    if as_type == "Bool":
        return "true" if value else "false"
    raise ValueError(as_type)


def generate_contract_swift(
    schema_texts: dict[str, str],
    channels: list[dict],
    parameters: list[dict],
    services: list[dict],
    types: dict,
) -> str:
    lines = [
        f"// {HEADER}",
        "",
        "import Foundation",
        "",
        "public enum Backpressure: String, Equatable, Sendable {",
        "    case latest",
        "    case queue",
        "    case keep",
        "}",
        "",
        "public enum ParameterValueType: String, Equatable, Sendable {",
        "    case number",
        "    case boolean",
        "    case string",
        "}",
        "",
        "public struct ChannelSpec: Equatable, Sendable {",
        "    public var key: String",
        "    public var topic: String",
        "    public var schema: String",
        "    public var frameId: String",
        "    public var childFrameId: String?",
        "    public var rateParam: String?",
        "    public var rateHz: Double?",
        "    public var backpressure: Backpressure",
        "    public var queueSeconds: Double?",
        "    public var group: String?",
        "    public var latched: Bool",
        "    public var stage: Int",
        "",
        "    public init(",
        "        key: String,",
        "        topic: String,",
        "        schema: String,",
        "        frameId: String,",
        "        childFrameId: String? = nil,",
        "        rateParam: String? = nil,",
        "        rateHz: Double? = nil,",
        "        backpressure: Backpressure,",
        "        queueSeconds: Double? = nil,",
        "        group: String? = nil,",
        "        latched: Bool,",
        "        stage: Int",
        "    ) {",
        "        self.key = key",
        "        self.topic = topic",
        "        self.schema = schema",
        "        self.frameId = frameId",
        "        self.childFrameId = childFrameId",
        "        self.rateParam = rateParam",
        "        self.rateHz = rateHz",
        "        self.backpressure = backpressure",
        "        self.queueSeconds = queueSeconds",
        "        self.group = group",
        "        self.latched = latched",
        "        self.stage = stage",
        "    }",
        "}",
        "",
        "public struct ParameterSpec: Equatable, Sendable {",
        "    public var name: String",
        "    public var type: ParameterValueType",
        "    public var defaultNumber: Double?",
        "    public var defaultBoolean: Bool?",
        "    public var defaultString: String?",
        "    public var min: Double?",
        "    public var max: Double?",
        "    public var choices: [String]?",
        "    public var writable: Bool",
        "    public var description: String",
        "}",
        "",
        "public struct ServiceSpec: Equatable, Sendable {",
        "    public var key: String",
        "    public var name: String",
        "    public var type: String",
        "    public var stage: Int",
        "}",
        "",
        "public enum ContractSchemas {",
        "    public static func text(for schemaName: String) -> String? {",
        "        switch schemaName {",
    ]
    for name in sorted(schema_texts):
        lines.append(f"        case {swift_string(name)}:")
        lines.append(f"            return {swift_string(schema_texts[name])}")
    lines.extend(
        [
            "        default:",
            "            return nil",
            "        }",
            "    }",
            "}",
            "",
            "public enum Contract {",
            "    public static let channels: [ChannelSpec] = [",
        ]
    )
    for row in channels:
        bp = row["backpressure"]
        lines.append("        ChannelSpec(")
        lines.append(f"            key: {swift_string(row['key'])},")
        lines.append(f"            topic: {swift_string(row['topic'])},")
        lines.append(f"            schema: {swift_string(row['schema'])},")
        lines.append(f"            frameId: {swift_string(row['frame_id'])},")
        lines.append(f"            childFrameId: {swift_optional(row.get('child_frame_id'), 'String')},")
        lines.append(f"            rateParam: {swift_optional(row.get('rate_param'), 'String')},")
        lines.append(f"            rateHz: {swift_optional(row.get('rate_hz'), 'Double')},")
        lines.append(f"            backpressure: .{bp},")
        lines.append(f"            queueSeconds: {swift_optional(row.get('queue_seconds'), 'Double')},")
        lines.append(f"            group: {swift_optional(row.get('group'), 'String')},")
        lines.append(f"            latched: {'true' if row['latched'] else 'false'},")
        lines.append(f"            stage: {int(row['stage'])}")
        lines.append("        ),")
    lines.append("    ]")
    lines.append("")
    lines.append("    public static let parameters: [ParameterSpec] = [")
    for row in parameters:
        ptype = row["type"]
        default = row["default"]
        default_number = "nil"
        default_boolean = "nil"
        default_string = "nil"
        if ptype == "number":
            default_number = repr(float(default))
        elif ptype == "boolean":
            default_boolean = "true" if default else "false"
        elif ptype == "string":
            default_string = swift_string(str(default))
        else:
            raise ValueError(f"unknown parameter type {ptype}")
        lines.append("        ParameterSpec(")
        lines.append(f"            name: {swift_string(row['name'])},")
        lines.append(f"            type: .{ptype},")
        lines.append(f"            defaultNumber: {default_number},")
        lines.append(f"            defaultBoolean: {default_boolean},")
        lines.append(f"            defaultString: {default_string},")
        lines.append(f"            min: {swift_optional(row.get('min'), 'Double')},")
        lines.append(f"            max: {swift_optional(row.get('max'), 'Double')},")
        lines.append(f"            choices: {swift_optional(row.get('choices'), '[String]')},")
        lines.append(f"            writable: {'true' if row['writable'] else 'false'},")
        lines.append(f"            description: {swift_string(row['description'])}")
        lines.append("        ),")
    lines.append("    ]")
    lines.append("")
    lines.append("    public static let services: [ServiceSpec] = [")
    for row in services:
        lines.append("        ServiceSpec(")
        lines.append(f"            key: {swift_string(row['key'])},")
        lines.append(f"            name: {swift_string(row['name'])},")
        lines.append(f"            type: {swift_string(row['type'])},")
        lines.append(f"            stage: {int(row['stage'])}")
        lines.append("        ),")
    lines.append("    ]")
    lines.append("}")
    lines.append("")
    lines.append("public enum ContractCodec {")
    lines.append("    public static func reencode(schemaName: String, cdr: Data) throws -> Data {")
    lines.append("        switch schemaName {")
    for typename in sorted(types):
        nominal = swift_nominal(typename)
        lines.append(f"        case {nominal}.schemaName:")
        lines.append("            var decoder = try CDRDecoder(data: cdr)")
        lines.append(f"            let msg = try {nominal}(from: &decoder)")
        lines.append("            var encoder = CDREncoder()")
        lines.append("            msg.encode(to: &encoder)")
        lines.append("            return encoder.data")
    lines.append("        default:")
    lines.append("            throw CDRError.unknownSchema(schemaName)")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_all() -> dict[Path, str]:
    msg_texts = load_msg_texts()
    types = parse_types(msg_texts)
    schema_texts = {name: schema_text_for(name, msg_texts, types) for name in msg_texts}
    channels = fill_rows(load_toml_table(CONTRACT / "channels.toml", "channel"), CHANNEL_KEYS)
    parameters = fill_rows(load_toml_table(CONTRACT / "parameters.toml", "parameter"), PARAMETER_KEYS)
    services = fill_rows(load_toml_table(CONTRACT / "services.toml", "service"), SERVICE_KEYS)
    files = {
        PY_GENERATED / "__init__.py": f"# {HEADER}\n",
        PY_GENERATED / "contract_data.py": generate_python(
            msg_texts, schema_texts, channels, parameters, services
        ),
        SWIFT_GENERATED / "Messages.generated.swift": generate_messages_swift(msg_texts, types),
        SWIFT_GENERATED / "Contract.generated.swift": generate_contract_swift(
            schema_texts, channels, parameters, services, types
        ),
    }
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate Swift and Python artifacts from contract/")
    parser.add_argument("--check", action="store_true", help="compare generated output with files on disk")
    args = parser.parse_args(argv)
    files = generate_all()
    if args.check:
        differed = []
        for path, content in files.items():
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if existing != content:
                differed.append(path)
        for path in differed:
            print(path.relative_to(REPO_ROOT) if path.is_relative_to(REPO_ROOT) else path)
        return 1 if differed else 0
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
